image:
  name: gcr.io/<your-gcp-project-id>/ml-model
  version: latest
service:
  port: 80
  type: ClusterIP
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
