serviceAccount:
  create: true
  name: ""
images:
  - name: get_health_fastapi
    tag: latest
    replicaCount: 1
    maxReplicas: 3
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - path: /latest/get_health_fastapi
      serviceName: get-health-fastapi-service
      servicePort: 8080
