apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  namespace: ml-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        {{- range .Values.images }}
        - name: {{ .name | replace "_" "-" }}
          image: "asia-southeast2-docker.pkg.dev/mycicdproject-426810/images/{{ .name }}:{{ .tag }}"
          ports:
            - containerPort: {{ .port }}
          resources:
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
        {{- end }}
