{{- range .Values.images }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}-hpa
  namespace: ml-models
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}
  minReplicas: {{ .replicaCount }}
  maxReplicas: {{ .maxReplicas }}
  targetCPUUtilizationPercentage: 80
{{- end }}
