{{- if not (hasKey .Release.Labels "meta.helm.sh/release-name") }}
apiVersion: v1
kind: Namespace
metadata:
  name: ml-models
  labels:
    app.kubernetes.io/managed-by: Helm
    {{- with .Values.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
{{- end }}
