{{- range .Values.images }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | replace "/" "-" }}-service
  namespace: ml-models
spec:
  selector:
    app: ml-model
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
